### ISSUE TITLE
unable to run commands on docker

### ISSUE THREAD

**Issue by ssbarnea** [dcrosta/tox-docker#3]
I tried to add `yum install something` to the list of `commands` from my `centos:centos7` container but I get an error `ERROR: invocation failed (errno 2), args: ['/bin/yum', '--help']`

I do mention that the file is inside the container and I successfully run:
```
docker run -t -i centos:centos7 yum --help
...
```
How am I supposed to run tox testing commands? Do I need some extra tickets to make it work?

Note: it seems that the problem is not related to PATH because I tried with full path and got same results.

For example I do have a complex command that I need to make it work under tox-docker:

    bash -c "{envbindir}/python -c 'import rpm' 2>/dev/null || /bin/yum install -q -y rpm-python"

This command is supposed to attempt to install `rpm` library if is missing, as this is a requirements for running the tests.

Pre-building a container with that tool installed is out of question for the moment. Anyway, I am afraid that there is something else that is wrong because I know that `yum`  is already installed in `/bin/yum` inside the container.

**Comment by dcrosta** [comment]
I think probably 90% or more cases where you would want to do this, you'll probably be better off making a new image, rather than trying to run commands against the container when it just comes up. Is this one of those cases? Or does your use case have to check some external state and make some decision on what commands to run?

My main use cases for tox-docker were things like "my tests need a PostgreSQL database to run; and I don't want to encode information about my developer envrionment, or our CI environment, into the tests; so let tox parameterize the tests via env vars, and let tox manage the docker container".

Tox-docker definitely _isn't_ "I want to run my tox tests inside a docker container". It doesn't do that at all; and I'm not even sure if you really sanely could with a tox plugin. However, based on a [quick PyPI search](https://pypi.python.org/pypi?%3Aaction=search&term=tox%20docker&submit=search), it looks like such tools exist. I have no experience with them, so YMMV.

**Comment by dcrosta** [comment]
(I'm closing this, but if you still have questions, just say so)
